import { Project } from '../models/project.model';
import {
  nestjs,
  redis,
  jwt,
  typeorm,
  mysql,
  typescript,
  momentjs,
  python,
  c,
  rpi,
  arduino,
  tensorflow,
  java,
  derby,
  android,
  ionic,
  angular,
  html,
  scss,
  ngrx,
  sqlite,
  mongodb,
  firebase,
  pyupload,
  pyqt5,
  ffmpeg,
  obsidian,
  md,
  mermaid,
  annyang,
  puppeteer,
  cheerio,
  nextjs,
  n8n,
  cloudFlare,
  githubActions,
  react,
  vite,
  githubPages,
  aws,
  docker,
  nodejs,
} from './technologies.provider';
import { PROJECT_TYPE } from '../enums/project-type.enum';

export const projects: Project[] = [
  // {
  //   name: 'Second Brain',
  //   started_at: 'Feb 2021',
  //   description:
  //     'Project that uses PARA method for organizing and indexing knowledge.',
  //   technologies: [obsidian, md, mermaid],
  //   icon_url: 'assets/images/projects/sb.jpg',
  //   type: PROJECT_TYPE.OTHERS,
  // },

  {
    name: 'Years Tracker V2',
    started_at: 'Feb 2026',
    finished_at: 'Feb 2026',
    description:
      'Revamp Version of Years Tracker: Years/Life Tracker is a web-based life visualization tool that maps progress from birthdate to a target lifespan. It displays years completed and remaining, offering a clear timeline perspective to support long-term planning and intentional decision-making.',
    technologies: [typescript, react, vite, githubPages, githubActions],
    icon_url: 'assets/images/projects/years-tracker.png',
    project_url: 'https://edisonesc.github.io/years-tracker-v2',
    type: PROJECT_TYPE.WEB,
    exclude_in_cv: true,
  },
  {
    name: 'NestJS Boilerplate',
    started_at: 'Feb 2026',
    finished_at: 'Feb 2026',
    description:
      'A scalable and production-ready NestJS boilerplate designed for clean architecture and rapid backend development. Includes structured domain modules, JWT authentication (access + refresh), TypeORM integration, environment-based configuration, and migration support.',
    technologies: [nestjs, nodejs, typeorm, mysql, jwt, docker],
    icon_url: 'assets/images/projects/NestJS.jpg',
    project_url: '',
    type: PROJECT_TYPE.SYSTEM,
    // exclude_in_cv: false,
  },
  {
    name: 'Expense Tracker Integration',
    started_at: 'Aug 2025',
    finished_at: 'Aug 2025',
    description:
      'Deployed n8n server full on-prem with KNUC and Cloudflare tunnels. Integrated Expense Google Sheet and Telegram API for easy updates and tracking of expenses.',
    technologies: [n8n, typescript, cloudFlare],
    type: PROJECT_TYPE.OTHERS,
    exclude_in_cv: false,
  },
  // {
  //   name: 'Reflex Trainer for boxing',
  //   started_at: 'Dec 2023',
  //   finished_at: 'Dec 2023',
  //   description:
  //     'Simple web app to learn defense and counter in boxing by simulating offensive strikes with adjustable pace.',
  //   technologies: [angular, typescript],
  //   type: PROJECT_TYPE.OTHERS,
  //   exclude_in_cv: true,
  // },
  {
    name: 'Content-Driven Portfolio Platform',
    started_at: 'Apr 2023',
    finished_at: 'Present',
    description:
      'Designed and built a configuration-driven frontend platform that generates dynamic portfolio content from structured data, with support for multiple output renderers, including a CV-style document. Includes CI for Unit Tests and CD setup support for AWS and Github Pages.',
    technologies: [angular, typescript, githubActions, githubPages, aws],
    type: PROJECT_TYPE.OTHERS,
    project_url: 'https://edisonesc.github.io/pages/home',
    // exclude_in_cv: true,
  },
  {
    name: 'Speech Command File Downloader',
    started_at: 'Apr 2021',
    finished_at: 'Apr 2021',
    description:
      'STT and TTS web application that takes audio inputs, scrapes data from a specific website using the translated audio information and download files via magnet link to a local transmission server.',
    technologies: [angular, typescript, nestjs, annyang, puppeteer, cheerio],
    type: PROJECT_TYPE.WEB,
    exclude_in_cv: true,
  },
  {
    name: 'Years Tracker',
    started_at: 'Feb 2021',
    finished_at: 'Feb 2021',
    description:
      'A personal tracker that tracks my existence and reflects time/years left before target year is met (default is 90 years).',
    technologies: [angular, typescript, momentjs, githubPages],
    icon_url: '',
    project_url: 'https://edisonesc.github.io/years-tracker/home/',
    type: PROJECT_TYPE.WEB,
    exclude_in_cv: true,
  },
  {
    name: 'Sammy API',
    started_at: 'Jan 2021',
    finished_at: 'Feb 2021',
    description:
      'Designed and developed a NestJS-based API that encapsulated all of Sammy’s offline features and handling synchronization flows',
    technologies: [
      nestjs,
      nodejs,
      redis,
      jwt,
      typeorm,
      mysql,
      typescript,
      momentjs,
    ],
    icon_url: '',
    type: PROJECT_TYPE.SYSTEM,
    // exclude_in_cv: true,
  },
  {
    name: 'Sammy',
    started_at: 'Oct 2020',
    finished_at: 'Dec 2020',
    description:
      "Mobile application developed using Ionic with Angular. It allows user to create, edit, delete workouts, exercises. The app can also handle Rep-based and Time-based exercise. They can also be able to share their workout to other users who's interested via QR Code.",
    technologies: [typescript, ionic, angular, html, scss, ngrx, sqlite],
    icon_url: '',
    type: PROJECT_TYPE.MOBILE,
    exclude_in_cv: true,
  },
  {
    name: 'Icons and Splash Genarator',
    started_at: 'Nov 2020',
    finished_at: 'Nov 2020',
    description:
      'Script that takes a file path and converts the image into various dimensions then uploads a download zip file and shares the download link.',
    technologies: [python, pyupload],
    icon_url: '',
    type: PROJECT_TYPE.OTHERS,
    exclude_in_cv: true,
  },
  {
    name: 'Saves',
    started_at: 'Feb 2020',
    finished_at: 'Mar 2020',
    description:
      "Mobile application developed using Ionic with Angular. Implemented state management using NgRx along with NestJS as backend framework and MongoDB for the database. It allows user to save items, add logs, images and track their progress on the item they're saving for.",
    technologies: [
      typescript,
      ionic,
      angular,
      html,
      scss,
      ngrx,
      sqlite,
      nestjs,
      mongodb,
    ],
    icon_url: '',
    type: PROJECT_TYPE.MOBILE,
    exclude_in_cv: true,
  },
  {
    name: 'Pantera',
    started_at: 'Feb 2018',
    finished_at: 'April 2019',
    description:
      'Semi-Autonomous Book Shelving Robot (CS thesis) integrating collision avoidance, QR matching, and line tracing. Trained a computer vision model for book spine detection and real-time gap estimation, enabling autonomous placement decisions based on available shelf space.',
    technologies: [python, c, rpi, arduino, tensorflow],
    icon_url: 'assets/images/projects/pantera.jpg',
    type: PROJECT_TYPE.SYSTEM,
    // project_url: '',
  },
  {
    name: 'OJT Hours Tracker App',
    started_at: 'Sep 2018',
    finished_at: 'Oct 2019',
    description:
      'Android mobile application built with Java and Firebase that logs time-in and time-out entries, automatically calculates total OJT hours, and stores records in real time. Designed to provide accurate attendance tracking, centralized cloud data storage, and easy monitoring of training hour compliance.',
    technologies: [java, android, firebase],
    icon_url: '',
    type: PROJECT_TYPE.MOBILE,
    exclude_in_cv: true,
  },
  {
    name: 'CVARST Medical System',
    started_at: 'Aug 2018',
    finished_at: 'Sep 2018',
    description:
      'CVARST-Act-Project is a Java-based (netbeans) application developed as part of an undergraduate academic requirement, implementing a modular CRUD system with login, registration, and management modules (e.g., doctor information and maintenance for tests).',
    technologies: [java, derby, mysql],
    icon_url: '',
    type: PROJECT_TYPE.SYSTEM,
    exclude_in_cv: true,
  },
  {
    name: 'Mp4 to Mp3-Converter',
    started_at: 'Aug 2018',
    finished_at: 'Sep 2018',
    description:
      'Python-based MP4 to MP3 converter with a simple PyQt5 GUI. Uses FFmpeg to batch-convert video files to MP3, supports source/destination selection, automatic file listing, and basic filename handling for special characters. Designed for quick local audio extraction from MP4 files.',
    technologies: [python, pyqt5, ffmpeg],
    icon_url: '',
    type: PROJECT_TYPE.OTHERS,
    exclude_in_cv: true,
  },
  {
    name: 'Vehicle Renting and Billing System',
    started_at: 'Jul 2017',
    finished_at: 'Aug 2017',
    description:
      'Project developed for a course using Java and embedded Derby database. It enables users to reserve, schedule and choose a vehicle for rent. It also enables admin to perform CRUD operations from the clients and vehicles.',
    technologies: [java, derby, mysql],
    icon_url: '',
    type: PROJECT_TYPE.SYSTEM,
    exclude_in_cv: true,
  },
  // {
  //   name: 'Reflex',
  //   started_at: 'Oct 2017',
  //   finished_at: 'Nov 2017',
  //   description:
  //     'A simple yet challenging mobile game that gets harder as you level up.',
  //   technologies: [java, android],
  //   icon_url: '',
  //   type: PROJECT_TYPE.MOBILE,
  //   exclude_in_cv: true,
  // },
  {
    name: 'Workout Generator & Nutrition Calculator',
    started_at: 'Jun 2017',
    finished_at: 'Jul 2017',
    description:
      'Mobile application project developed for a course using Java. It calculates your BMR, BMI, water intake, and total calorie intake base on how often you exercise. It also generates workouts for beginners, intermediates, and advanced, macro intake, and meal distribution.',
    technologies: [java, android],
    icon_url: '',
    type: PROJECT_TYPE.MOBILE,
    exclude_in_cv: true,
  },
  // {
  //   name: 'Workout Program Generator',
  //   started_at: 'Apr 2017',
  //   finished_at: 'Apr 2017',
  //   description:
  //     'Simple project developed for a course using Java. It generates workouts for users whether the user is a beginner, intermediate, and advanced. Users can choose whether they want to only use bodyweight, weights, or mixed.',
  //   technologies: [java],
  //   icon_url: '',
  //   type: PROJECT_TYPE.SYSTEM,
  //   exclude_in_cv: true,
  // },
];
